server:
  port:
    9001
spring:
  application:
    name: SpringCacheRedisApplication
  redis:
    model: standalone
    url: localhost
    port: 6397
  cache:
    type: redis
  jpa:
    hibernate:
      ddl-auto: update
      dialect: sql
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/spring_boot?serverTimezone=UTC
    username: root
    password: root




