spring:
  shardingsphere:
    datasource:
      names: master,slave-0,slave-1
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/asx?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
        username: root
        password: root
      slave-0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3307/asx?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
        username: root
        password: root
      slave-1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3308/asx?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
        username: root
        password: root
    sharding:
      tables:
        t_order:
          key-generator:
            column: order_id
            type: SNOWFLAKE
          actual-data-nodes: ms.t_order_$->{0..1}
          database-strategy:
            inline:
              sharding-column: order_id
              algorithm-expression: ms
          table-strategy:
            inline:
              sharding-column: order_id
              algorithm-expression: t_order_$->{order_id % 2}
        t_order_item:
          key-generator:
            column: item_id
            type: SNOWFLAKE
          actual-data-nodes: ms.t_order_item_$->{0..1}
          database-strategy:
            inline:
              sharding-column: order_id
              algorithm-expression: ms
          table-strategy:
            inline:
              sharding-column: order_id
              algorithm-expression: t_order_item_$->{order_id % 2}
      binding-tables: t_order,t_order_item
      broadcast-tables: t_config
#      default-data-source-name: master
      defaultTableStrategy:
        none:
        defaultKeyGenerator:
          type: SNOWFLAKE
          column: order_id
      masterSlaveRules:
        ms:
          masterDataSourceName: master
          slaveDataSourceNames:
            - slave-0
            - slave-1
          loadBalanceAlgorithmType: ROUND_ROBIN
    props:
      sql:
        show: true                                          # 打印SQL
