server:
  port: 9380

spring:
  application:
    name: sharding-mybatis-plus
logging:
  level:
    root: info
    pers:
      demo:
        asa:
          spring:
            data:
              mybatis:
                plus:
                  mysql:
                    mapper: info
  pattern:
    console: '%p%m%n'

