spring:
  rabbitmq:
    username: root
    password: root
    publisher-confirms: true    #确认消息已发送到交换机(Exchange)
    publisher-returns: true     #确认消息已发送到队列(Queue)
    listener:
      simple:
        acknowledge-mode: manual
    addresses: 0.0.0.0:5073