server:
  port: 9380

spring:
  application:
    name: dynamic-datasource-app
logging:
  level:
    root: info
    pers:
      demo:
        asa:
          spring:
            data:
              mybatis:
                plus:
                  mysql:
                    mapper: info
  pattern:
    console: '%p%m%n'

mybatis:
  type-aliases-package: com.asa.demo.model
  mapper-locations: classpath*:mapper/*.xml

