spring:
  application:
    name: SpringBootCfgApp
server:
  port: 9400

self:
  version: 1.0
  params:
    defaultUrl: 10.0.0.1
    biz:
      vo: 10.0.0.vo
      ali: 10.0.0.ali
      kof: 10.0.0.kof
    companyIds:
      - 1
      - 2

#config:
#  property:
#    subscribe: book

