spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: root
    virtual-host: pers-xrb
    listener:
      direct:
        retry:
          max-attempts: 3
      simple:
        retry:
          max-attempts: 3
        acknowledge-mode: manual