spring:
  rabbitmq:
    host: 0.0.0.0
    port: 5674
    username: root
    password: root
#    virtual-host: pers-xrb
    listener:
      direct:
        retry:
          max-attempts: 3
      simple:
        retry:
          max-attempts: 3
        acknowledge-mode: manual