#server:
#  port: 9002

spring:
  application:
    name: SpringBootDBApplication

  #      uri: mongodb://localhost:27017/spring-data
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      #      authentication-database: admin
      database: spring-data
#      username: root
#      password: 123456

logging:
  level:
    root=DEBUG:


